on: [push, pull_request]
name: Testing & Coverage
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.8, 1.17.x]
        os: [fedora-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: install libgpgme
      run: sudo apt-get install -y libgpgme-dev || sudo dnf install -y gpgme-devl
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -mod=vendor -v -coverprofile cover.out ./pkg/...
    - name: Upload Coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./cover.out
        verbose: true